### ISSUE TITLE
Notification showing all messages, but in-app only shows last message

### ISSUE THREAD

**Issue by bleader** [murgo/IrssiNotifier#201] opened 2018-11-17 14:03 UTC
Looks pretty similar to #144 but appeared after 1.9 update.

I cleared all channels to see if it was related, but didn't change, but makes result more obvious:

- receive X messages
- get notification with X messages
- in app only the last one is shown in feed, it is populated in the correct channel, and every other channels are empty, Even if there were other messages before that weren't cleared manually.

Note: I say channel, but channels and queries were tested.

 Happens to me and a friend, our devices:
- one plus 5, android 8.1.0
- nexus 5x, android 7.1.2
both using IrssiNotifier 1.9.1, we both had an outdated script, but updated it and issue is still there (profile page confirms that script is up to date).

**Comment by murgo** [comment] 2018-11-17 16:30
Hmm, this does not happen to me on Oneplus 3t. Needs investigating. Is the issue only when receiving multiple notifications at the same time before opening the app, or does the app not show any old messages?

**Comment by bleader** [comment] 2018-11-17 16:47
As far as I can tell it does not show any old messages, they're always cleared and only the last one is kept. If I can do anything to help let me know!

**Comment by MacGyverNL** [comment] 2018-11-18 16:09
Also happening for me on a stock Galaxy S5 mini, android 6.0.1, irssinotifier 1.9.1, precisely according to description given. Was working fine before this update. I did have to reselect my google account after the update, maybe that's relevant?

**Comment by bleader** [comment] 2018-11-18 18:13
I totally forgot to mention it, but  we had to reselect our account too after the update, both my friend and I.

**Comment by murgo** [comment] 2018-11-18 21:56
Yeah, everyone has to re-select the account, that is normal and unrelated.

su 18. marrask. 2018 klo 20.13 bleader <notifications@github.com> kirjoitti:

**Comment by murgo** [comment] 2018-11-25 22:31
I can't reproduce this on IrssiNotifier or IrssiNotifier+ and I wonder if it's related to the upgrade to the last version of the app.

Could someone try totally removing the app and then installing the app again to see if issue still persists?

**Comment by MacGyverNL** [comment] 2018-11-25 23:00
Issue persists.

Cleared data + cache, uninstalled app, restarted phone, installed irssinotifier, opened, set encryption password.

**Comment by MacGyverNL** [comment] 2018-11-25 23:30
I never see any old messages, regardless from where I open the app. Only the most recent message is shown in both cases. It is never entirely empty.

**Comment by MacGyverNL** [comment] 2018-11-26 00:17
Also, with the app open, and a new notification coming in, I simply see the new message overwrite the old one.

**Comment by johnruemker** [comment] 2018-11-30 13:06
Same issue.  I'm a new user that just installed yesterday.  Every irc mention notifies me, but only the last one gets displayed in the app.   Even with messages from separate channels, only the channel for the last message shows content.  The feed always just shows the one message.

**Comment by murgo** [comment] 2018-11-30 21:31
If someone with the issue could check their phone logs (logcat) while starting the app and getting a notification it might contain something relevant. I just tried clearing all and reinstalling and nope, works fine.

**Comment by johnruemker** [comment] 2018-11-30 23:33
Nothing new shows up in logcat either when starting the app or getting a notification.

**Comment by jheidel** [comment] 2018-12-02 00:06
I'm also seeing this problem (Pixel 3, Android 9 Pie). Any incoming message will clear history of all saved messages. I've done some debugging and think I've identified the issue.

In `DataAccess.handleMessage`, `isNew` is always false so `database.update` is always called and the database is presumably wiped for each message. This explains the lost history.

`isNew` appears to be false because `IrcMessage.getExternalId()` returns null.

The `message` field in `FancyFcmListenerService.onMessageReceived` contains the following:
```
{"nick": "...snipped...", "message": "...snipped...", "server_timestamp": "1543707718.000000", "id": null, "channel": "...snipped..."}
```
and the null `id` here explains the null `IrcMessage.getExternalId()` because it will not be populated by `IrcMessage.deserialize()`.

Manually setting the ID from the ID provided by the `remoteMessage` object appears to fix the issue (see PR https://github.com/murgo/IrssiNotifier/pull/202).

I have no background on firebase messaging or what this ID is supposed to represent in the app, so I'm not sure if this is the correct fix. Let me know if any additional debugging would be useful.

**Comment by murgo** [comment] 2018-12-02 02:37
Hey thanks @jheidel, this will help fixing the bug very much.

If I recall correctly (and read this right), the external ID (actually just database id of the message in the server) actually should be null for free users since their messages are not persisted in the server, so this might be Irssinotifier vs Irssinotifier+ issue (would also explain why I'm not seeing it). External Id is used to match messages that came via push notifications and messages fetched on app start (IrssiNotifier+ feature) so duplicate messages are merged.

I'm not exactly sure why you get those results though. If the `message.getExternalID()` is null, `isNew` of `DataAccess.handleMessage()` should never be able to become false (since there is a null check just above setting it to false). All free user messages should be new since they can only come via the push service and they should never be updated.

I'm a bit perplexed since the external ID _should_ be null for free users yet your fix fixes the app for you? Do you have IrssiNotifier+?

It might very well be related to the external id anyway, and this will point me in the right direction. Possible the field called "id" shouldn't be used for own data in FCM or something.

**Comment by jheidel** [comment] 2018-12-02 02:50
Hmm... right, looking at the code closer I agree, a null `message.getExternalId()` should leave `isNew` as true. I was definitely seeing `isNew` as false in that method though which was causing it to always hit the `database.update` path when stepping through with the debugger. I'll look at that more closely in the debugger and get back to you...

Yes, I'm using the free version and I don't have IrssiNotifier+ which explains the null external ID.

**Comment by jheidel** [comment] 2018-12-02 02:56
Ah! So the problem is that `message.getExternalId()` at DataAccess.java:83 is returning the string "null", not a null value.

Copying the value of `obj` from the call to `IrcMessage.deserialize()`, I get this:
{"nick":"U2FsdGVkX182VMT0ZzyoLXdslha3L1vvTY0mLRU76bk","message":"U2FsdGVkX18ObalUmN34Tuum5O9bu-CMh5BbConTZ00","server_timestamp":"1543719224.000000","id":null,"channel":"U2FsdGVkX198SA_P0y2cSozxq4aWDXDHHvra2EBwrFE"}

However IrcMessage.java:31 is doing a string conversion and producing the value "null".

**Comment by murgo** [comment] 2018-12-02 04:34
Oops didn't mean to close this just yet, apparently GitHub does that on merge. I just released a new version of the app to Google Play that should have this fixed, so when update is live I'll close this tomorrow if issue is fixed for everyone.

**Comment by Superdawg** [comment] 2018-12-02 04:50
I just got the update on Google Play, and I've been able to confirm that the bug appears to be resolved for me on a Pixel 2 XL running Android 9.  Thank you everyone for the fix!

**Comment by murgo** [comment] 2018-12-02 04:53
That's great! Thanks everyone for reporting and thanks @jheidel for debugging <3

**Closed by murgo** 2018-12-02 04:53 UTC

**Comment by johnruemker** [comment] 2018-12-02 04:54
Fixed!  Great work both.  Thanks

**Comment by bleader** [comment] 2018-12-02 09:38
Yep, working great, thanks @murgo and @jheidel.
